name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: tenmenezes
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
          default_author: github_actions
